project:
  type: website
  resources:
    - "files/**"
    - "etc/**"

website:
  title: "Qinyu Xiao"
  site-url: https://qinyuxiao.rbind.io
  description: "Qinyu Xiao is a PhD student at the University of Vienna, studying cooperation, prosociality, and social institutions."
  comments:
    utterances: 
      repo: qinyuxiao/qinyu-xiao-website
  navbar:
    pinned: true
    background: "#0063A6"
    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Research"
        href: research

format:
  html:
    theme: cosmo
    css: styles.css